// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: managementpb/filter.proto

package managementpb

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Checks for results whose key is equal to the provided scalar value.
type EqualsStringFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EqualsStringFilter) Reset() {
	*x = EqualsStringFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EqualsStringFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EqualsStringFilter) ProtoMessage() {}

func (x *EqualsStringFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EqualsStringFilter.ProtoReflect.Descriptor instead.
func (*EqualsStringFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{0}
}

func (x *EqualsStringFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EqualsIntFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EqualsIntFilter) Reset() {
	*x = EqualsIntFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EqualsIntFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EqualsIntFilter) ProtoMessage() {}

func (x *EqualsIntFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EqualsIntFilter.ProtoReflect.Descriptor instead.
func (*EqualsIntFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{1}
}

func (x *EqualsIntFilter) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type EqualsLongFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EqualsLongFilter) Reset() {
	*x = EqualsLongFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EqualsLongFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EqualsLongFilter) ProtoMessage() {}

func (x *EqualsLongFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EqualsLongFilter.ProtoReflect.Descriptor instead.
func (*EqualsLongFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{2}
}

func (x *EqualsLongFilter) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Checks for results whose key is not equal to the provided string value.
type NotEqualsStringFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NotEqualsStringFilter) Reset() {
	*x = NotEqualsStringFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotEqualsStringFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotEqualsStringFilter) ProtoMessage() {}

func (x *NotEqualsStringFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotEqualsStringFilter.ProtoReflect.Descriptor instead.
func (*NotEqualsStringFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{3}
}

func (x *NotEqualsStringFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Checks for results whose key is not equal to the provided int32 value.
type NotEqualsIntFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NotEqualsIntFilter) Reset() {
	*x = NotEqualsIntFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotEqualsIntFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotEqualsIntFilter) ProtoMessage() {}

func (x *NotEqualsIntFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotEqualsIntFilter.ProtoReflect.Descriptor instead.
func (*NotEqualsIntFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{4}
}

func (x *NotEqualsIntFilter) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Checks for results whose key is not equal to the provided int64 value.
type NotEqualsLongFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NotEqualsLongFilter) Reset() {
	*x = NotEqualsLongFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotEqualsLongFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotEqualsLongFilter) ProtoMessage() {}

func (x *NotEqualsLongFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotEqualsLongFilter.ProtoReflect.Descriptor instead.
func (*NotEqualsLongFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{5}
}

func (x *NotEqualsLongFilter) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Returns results whose key lies within the inclusive range of the provided minimum and maximum values.
// Valid for (IntRangeValues).
type BetweenIntFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Minimum value in the range.
	Minimum int32 `protobuf:"varint,1,opt,name=minimum,proto3" json:"minimum,omitempty"`
	// Maximum value in the range.
	Maximum int32 `protobuf:"varint,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
}

func (x *BetweenIntFilter) Reset() {
	*x = BetweenIntFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetweenIntFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetweenIntFilter) ProtoMessage() {}

func (x *BetweenIntFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetweenIntFilter.ProtoReflect.Descriptor instead.
func (*BetweenIntFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{6}
}

func (x *BetweenIntFilter) GetMinimum() int32 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

func (x *BetweenIntFilter) GetMaximum() int32 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

// Checks for results whose key exists in a given array.
type InStringFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *InStringFilter) Reset() {
	*x = InStringFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InStringFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InStringFilter) ProtoMessage() {}

func (x *InStringFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InStringFilter.ProtoReflect.Descriptor instead.
func (*InStringFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{7}
}

func (x *InStringFilter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type InIntFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *InIntFilter) Reset() {
	*x = InIntFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InIntFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InIntFilter) ProtoMessage() {}

func (x *InIntFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InIntFilter.ProtoReflect.Descriptor instead.
func (*InIntFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{8}
}

func (x *InIntFilter) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type InLongFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int64 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *InLongFilter) Reset() {
	*x = InLongFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InLongFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InLongFilter) ProtoMessage() {}

func (x *InLongFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InLongFilter.ProtoReflect.Descriptor instead.
func (*InLongFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{9}
}

func (x *InLongFilter) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Checks for results whose key contains value as a substring
// Valid for (string_values).
type ContainsStringFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Value to search results in.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ContainsStringFilter) Reset() {
	*x = ContainsStringFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managementpb_filter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainsStringFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsStringFilter) ProtoMessage() {}

func (x *ContainsStringFilter) ProtoReflect() protoreflect.Message {
	mi := &file_managementpb_filter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsStringFilter.ProtoReflect.Descriptor instead.
func (*ContainsStringFilter) Descriptor() ([]byte, []int) {
	return file_managementpb_filter_proto_rawDescGZIP(), []int{10}
}

func (x *ContainsStringFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_managementpb_filter_proto protoreflect.FileDescriptor

var file_managementpb_filter_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x12, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x27, 0x0a, 0x0f, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x49, 0x6e, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x45, 0x71,
	0x75, 0x61, 0x6c, 0x73, 0x4c, 0x6f, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a, 0x15, 0x4e, 0x6f, 0x74, 0x45, 0x71, 0x75, 0x61, 0x6c,
	0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73,
	0x49, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x2b, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x4c, 0x6f, 0x6e, 0x67,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x10,
	0x42, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x49, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61,
	0x78, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x78,
	0x69, 0x6d, 0x75, 0x6d, 0x22, 0x28, 0x0a, 0x0e, 0x49, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x25,
	0x0a, 0x0b, 0x49, 0x6e, 0x49, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x0c, 0x49, 0x6e, 0x4c, 0x6f, 0x6e, 0x67, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x2c, 0x0a,
	0x14, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x8e, 0x01, 0x0a, 0x0e,
	0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x0b,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x72, 0x63, 0x6f, 0x6e,
	0x61, 0x2f, 0x70, 0x6d, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x4d, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0xca, 0x02, 0x0a, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0xe2, 0x02, 0x16, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0a, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_managementpb_filter_proto_rawDescOnce sync.Once
	file_managementpb_filter_proto_rawDescData = file_managementpb_filter_proto_rawDesc
)

func file_managementpb_filter_proto_rawDescGZIP() []byte {
	file_managementpb_filter_proto_rawDescOnce.Do(func() {
		file_managementpb_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_managementpb_filter_proto_rawDescData)
	})
	return file_managementpb_filter_proto_rawDescData
}

var file_managementpb_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_managementpb_filter_proto_goTypes = []interface{}{
	(*EqualsStringFilter)(nil),    // 0: management.EqualsStringFilter
	(*EqualsIntFilter)(nil),       // 1: management.EqualsIntFilter
	(*EqualsLongFilter)(nil),      // 2: management.EqualsLongFilter
	(*NotEqualsStringFilter)(nil), // 3: management.NotEqualsStringFilter
	(*NotEqualsIntFilter)(nil),    // 4: management.NotEqualsIntFilter
	(*NotEqualsLongFilter)(nil),   // 5: management.NotEqualsLongFilter
	(*BetweenIntFilter)(nil),      // 6: management.BetweenIntFilter
	(*InStringFilter)(nil),        // 7: management.InStringFilter
	(*InIntFilter)(nil),           // 8: management.InIntFilter
	(*InLongFilter)(nil),          // 9: management.InLongFilter
	(*ContainsStringFilter)(nil),  // 10: management.ContainsStringFilter
}
var file_managementpb_filter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_managementpb_filter_proto_init() }
func file_managementpb_filter_proto_init() {
	if File_managementpb_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_managementpb_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EqualsStringFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EqualsIntFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EqualsLongFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotEqualsStringFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotEqualsIntFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotEqualsLongFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetweenIntFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InStringFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InIntFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InLongFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managementpb_filter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainsStringFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_managementpb_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_managementpb_filter_proto_goTypes,
		DependencyIndexes: file_managementpb_filter_proto_depIdxs,
		MessageInfos:      file_managementpb_filter_proto_msgTypes,
	}.Build()
	File_managementpb_filter_proto = out.File
	file_managementpb_filter_proto_rawDesc = nil
	file_managementpb_filter_proto_goTypes = nil
	file_managementpb_filter_proto_depIdxs = nil
}
